# Generated by Django 6.0.1 on 2026-01-10 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnova', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='sujet',
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.RemoveField(
            model_name='cours',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='eleves',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cours/'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learnova.module')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnova.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_inscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu_texte', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='learnova.module')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termine', models.BooleanField(default=False)),
                ('date_fin', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnova.lecon')),
            ],
        ),
        migrations.DeleteModel(
            name='Contenu',
        ),
        migrations.DeleteModel(
            name='Sujet',
        ),
    ]
