# Generated by Django 6.0.1 on 2026-01-11 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnova', '0002_remove_cours_sujet_alter_cours_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='telephone',
        ),
        migrations.AddField(
            model_name='profil',
            name='cours_suivis',
            field=models.ManyToManyField(blank=True, related_name='etudiants', to='learnova.cours'),
        ),
        migrations.AddField(
            model_name='profil',
            name='image',
            field=models.ImageField(blank=True, upload_to='profils/'),
        ),
        migrations.CreateModel(
            name='ResultatEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('date_passage', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnova.evaluation')),
            ],
        ),
    ]
